# Generated by Django 2.0.7 on 2018-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBasic', '0002_auto_20180727_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagedata', models.ImageField(upload_to='userpost_data')),
                ('Describe', models.CharField(max_length=256)),
            ],
        ),
    ]
