# Generated by Django 2.0.7 on 2018-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBasic', '0005_auto_20180728_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='Imagedata',
            field=models.ImageField(upload_to='uploaded_pics'),
        ),
    ]
