# Generated by Django 2.0.7 on 2018-08-02 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBasic', '0009_auto_20180729_0854'),
        ('AppBasic', '0005_auto_20180728_1937(1)'),
        ('AppBasic', '0007_auto_20180728_2039(1)'),
        ('AppBasic', '0006_auto_20180728_2020(1)'),
    ]

    operations = [
    ]
